DELETE FROM wlddb.glossary;
LOAD DATA LOCAL 
	INFILE '{CSVDIR}/termcfg.csv' 
	INTO TABLE wlddb.glossary 
	CHARACTER SET {CHSET} 
	FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' 
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES 
	(`type`, `no`, name)
;
