DELETE FROM wlddb.port;
LOAD DATA LOCAL 
	INFILE '{CSVDIR}/port.csv' 
	INTO TABLE wlddb.port 
	CHARACTER SET {CHSET} 
	FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' 
	LINES TERMINATED BY '\n'
	(`no`, name)
;
