/* [create table yc] : */
CREATE TABLE IF NOT EXISTS `yc` (
	`station` INTEGER DEFAULT 1,
	`no` INTEGER DEFAULT 1,
	`name` TEXT DEFAULT '',
	`desc` TEXT DEFAULT '',
	`channel` INTEGER DEFAULT 1,
	`rtu` INTEGER  DEFAULT 1,
	`address` INTEGER DEFAULT 1,
	`addrres` INTEGER DEFAULT 1,
	`powerbay` INTEGER DEFAULT 0 ,
	`device` INTEGER DEFAULT 0,
	`type` INTEGER  DEFAULT 0,
	`unit` INTEGER DEFAULT 0 ,
	`maxval` INTEGER DEFAULT 1 ,
	`minval` INTEGER DEFAULT 1 ,
	`modulus` INTEGER DEFAULT 1 ,
	`offset` INTEGER DEFAULT 0.0 ,
	`decimal` INTEGER DEFAULT 2 ,
	`manualval` INTEGER  DEFAULT 0.0,
	`zero` INTEGER DEFAULT 0.0 ,
	`low1` INTEGER DEFAULT 0.0 ,
	`high1` INTEGER DEFAULT 0.0 ,
	`low2` INTEGER DEFAULT 0.0 ,
	`high2` INTEGER DEFAULT 0.0 ,
	`back` INTEGER DEFAULT 0.0 ,
	`picture` TEXT DEFAULT '',
	`storage` INTEGER DEFAULT 0 ,
	`storagesec` INTEGER DEFAULT 0 ,
	`attachyx` INTEGER DEFAULT 0 ,
	`attribute` INTEGER DEFAULT 0x2 ,
	`alarm` INTEGER DEFAULT 0 ,
	`statistic` INTEGER DEFAULT 0 ,
	`volalarm` INTEGER DEFAULT 0x0aa ,
	`volstatistic` INTEGER DEFAULT 0 ,
	`rvalue` INTEGER DEFAULT 0,
	`rattribute` INTEGER DEFAULT 0x8,
	`rwarnstatus` INTEGER DEFAULT 0,
	PRIMARY KEY (`station`,`no`),
	UNIQUE (`channel`,`rtu`,`address`)
)  ;
/* <INSERT yc> : */
INSERT INTO `yc`( `station`,`channel`,`rtu`,  `no`,   `name` ,   `desc`,  `address`,`addrres`,`powerbay`,`device`,`type`,`unit`,`maxval`,`minval`,`modulus`,`offset`,`decimal`,`manualval`,`zero`,`low1`,`high1`,`low2`,`high2`,`back`,  `picture`,`storage`,`storagesec`,`attachyx`,`attribute`,`alarm`,  `statistic`,`volalarm`,`volstatistic`) 
VALUES (          {0},   {1}, {2},{3},'{4}' ,'{5}',0x0{6},  0x0{7},  {8},  {9},{10},{11},{12},{13},  {14}, {15}, {16},  {17}   ,{18},{19},{20},{21},{22},{23},'{24}',{25}, {26},     {27},    {28},{29},{30},{31},{32});
